# Generated by Django 5.2.6 on 2025-09-03 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Hãng sản xuất')),
                ('model_name', models.CharField(max_length=100, verbose_name='Tên dòng máy')),
                ('cpu', models.CharField(blank=True, max_length=100)),
                ('ram_gb', models.IntegerField(blank=True, null=True, verbose_name='RAM (GB)')),
                ('storage', models.CharField(blank=True, max_length=100, verbose_name='Ổ cứng')),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=50, unique=True, verbose_name='Mã tài sản')),
                ('serial', models.CharField(max_length=100, unique=True, verbose_name='Số Serial')),
                ('purchase_date', models.DateField(verbose_name='Ngày mua')),
                ('warranty_expiry', models.DateField(verbose_name='Ngày hết hạn bảo hành')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('IN_STOCK', 'Trong kho'), ('ASSIGNED', 'Đã cấp phát'), ('RESERVED', 'Đã đặt trước'), ('REPAIR', 'Đang sửa chữa'), ('RETIRED', 'Hỏng (Chờ thanh lý)'), ('DISPOSED', 'Đã thanh lý')], default='IN_STOCK', max_length=20)),
                ('remark', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('assigned_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.department', verbose_name='Phòng ban giữ')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computers', to='organizations.employee', verbose_name='Người giữ')),
                ('current_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.location', verbose_name='Vị trí hiện tại')),
                ('computer_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='computers', to='assets.computermodel', verbose_name='Dòng máy')),
            ],
        ),
    ]
