# Generated by Django 5.2.6 on 2025-09-03 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('organizations', '0002_remove_employee_position_alter_department_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='warranty_expiry',
        ),
        migrations.RemoveField(
            model_name='computermodel',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='computermodel',
            name='ram_gb',
        ),
        migrations.RemoveField(
            model_name='computermodel',
            name='storage',
        ),
        migrations.AlterField(
            model_name='computer',
            name='asset_tag',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='assigned_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.department'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computers', to='organizations.employee'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='computer_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='computers', to='assets.computermodel'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='current_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.location'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='purchase_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='computer',
            name='serial',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='status',
            field=models.CharField(choices=[('IN_STOCK', 'Trong kho'), ('ASSIGNED', 'Đã cấp phát'), ('REPAIR', 'Đang sửa chữa'), ('DISPOSED', 'Đã thanh lý')], default='IN_STOCK', max_length=20),
        ),
        migrations.AlterField(
            model_name='computermodel',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='computermodel',
            name='model_name',
            field=models.CharField(max_length=100),
        ),
    ]
