# Generated by Django 5.2.6 on 2025-09-03 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTxn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Mã chứng từ')),
                ('type', models.CharField(choices=[('RECEIPT', 'Nhập kho'), ('ISSUE', 'Xuất cấp phát'), ('RETURN', 'Thu hồi/Trả về'), ('TRANSFER', 'Điều chuyển'), ('REPAIR_OUT', 'Gửi đi sửa'), ('REPAIR_IN', 'Nhập về từ nơi sửa'), ('DISPOSAL', 'Thanh lý')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('SUBMITTED', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối'), ('POSTED', 'Đã ghi sổ')], default='DRAFT', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_txns', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_txns', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.department', verbose_name='Phòng ban yêu cầu')),
                ('dest_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dest_txns', to='organizations.location')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_txns', to='organizations.employee')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_txns', to='organizations.employee')),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_txns', to='organizations.location')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTxnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.computer')),
                ('inventory_txn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.inventorytxn')),
            ],
        ),
    ]
