# Generated by Django 5.2.6 on 2025-09-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorytxn',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='inventorytxn',
            name='department',
        ),
        migrations.RemoveField(
            model_name='inventorytxn',
            name='issued_by',
        ),
        migrations.RemoveField(
            model_name='inventorytxn',
            name='status',
        ),
        migrations.RemoveField(
            model_name='inventorytxnline',
            name='note',
        ),
        migrations.AlterField(
            model_name='inventorytxn',
            name='code',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='inventorytxn',
            name='type',
            field=models.CharField(choices=[('ISSUE', 'Xuất cấp phát'), ('RETURN', 'Thu hồi/Trả về')], max_length=20),
        ),
    ]
